
export interface Review {
  id: string;
  name: string;
  countryCode: string;
  countryName: string;
  rating: number;
  text: string;
  timeAgo: string;
}

export const REVIEWS: Review[] = [
  // USA (20)
  { id: 'us-1', name: 'James Anderson', countryCode: 'US', countryName: 'USA', rating: 5, text: '“My friend literally thought I was joking when I said the app was this smooth.” 😂', timeAgo: '2 days ago' },
  { id: 'us-2', name: 'Michael Carter', countryCode: 'US', countryName: 'USA', rating: 5, text: '“I still check every day to make sure the consistency remains the same.” 👀', timeAgo: '1 week ago' },
  { id: 'us-3', name: 'Daniel Walker', countryCode: 'US', countryName: 'USA', rating: 4, text: '“The interface just feels comfortable to use honestly.”', timeAgo: '3 weeks ago' },
  { id: 'us-4', name: 'Ethan Brooks', countryCode: 'US', countryName: 'USA', rating: 5, text: '“I expected unnecessary complications but everything was straightforward.” ✅', timeAgo: '1 month ago' },
  { id: 'us-5', name: 'Ryan Mitchell', countryCode: 'US', countryName: 'USA', rating: 5, text: '“The support guy explained things better than I expected.” 👍', timeAgo: '2 months ago' },
  { id: 'us-6', name: 'Sophia Johnson', countryCode: 'US', countryName: 'USA', rating: 4, text: '“I’m still cautious but so far I can’t complain.”', timeAgo: '3 months ago' },
  { id: 'us-7', name: 'Emily Parker', countryCode: 'US', countryName: 'USA', rating: 5, text: '“I tested it with a small amount first because online trust is hard these days.” 💭', timeAgo: '4 months ago' },
  { id: 'us-8', name: 'Olivia Morgan', countryCode: 'US', countryName: 'USA', rating: 5, text: '“The dashboard is clean without trying too hard.” ✨', timeAgo: '5 months ago' },
  { id: 'us-9', name: 'Charlotte Evans', countryCode: 'US', countryName: 'USA', rating: 4, text: '“I didn’t even need help finding my way around.”', timeAgo: '6 months ago' },
  { id: 'us-10', name: 'Ava Thompson', countryCode: 'US', countryName: 'USA', rating: 5, text: '“Most platforms overwhelm me but this one feels calm.” 😌', timeAgo: '7 months ago' },
  { id: 'us-11', name: 'Benjamin Harris', countryCode: 'US', countryName: 'USA', rating: 5, text: '“I kept delaying joining until my colleague showed me his experience.”', timeAgo: '8 months ago' },
  { id: 'us-12', name: 'Matthew Collins', countryCode: 'US', countryName: 'USA', rating: 5, text: '“The app runs smoother than some banking apps honestly.” 📱', timeAgo: '9 months ago' },
  { id: 'us-13', name: 'Christopher Reed', countryCode: 'US', countryName: 'USA', rating: 4, text: '“I’m watching long term before getting too comfortable.” ⏳', timeAgo: '10 months ago' },
  { id: 'us-14', name: 'Nathan Cooper', countryCode: 'US', countryName: 'USA', rating: 5, text: '“The whole thing feels professionally arranged.”', timeAgo: '11 months ago' },
  { id: 'us-15', name: 'Alexander White', countryCode: 'US', countryName: 'USA', rating: 5, text: '“I was expecting delayed withdrawals but mine came through normally.” 💸', timeAgo: '1 year ago' },
  { id: 'us-16', name: 'Grace Wilson', countryCode: 'US', countryName: 'USA', rating: 5, text: '“The support team deserves some credit honestly.”', timeAgo: '1 year ago' },
  { id: 'us-17', name: 'Victoria Lewis', countryCode: 'US', countryName: 'USA', rating: 4, text: '“I thought people were overhyping it at first.” 🤨', timeAgo: '1 year ago' },
  { id: 'us-18', name: 'Madison Clark', countryCode: 'US', countryName: 'USA', rating: 5, text: '“The experience has been stress free for me so far.”', timeAgo: '1 year ago' },
  { id: 'us-19', name: 'Abigail Scott', countryCode: 'US', countryName: 'USA', rating: 5, text: '“Everything updates surprisingly fast.” ⚡', timeAgo: '2 years ago' },
  { id: 'us-20', name: 'Hannah Rivera', countryCode: 'US', countryName: 'USA', rating: 5, text: '“The registration process didn’t give me a headache.”', timeAgo: '2 years ago' },

  // UK (20)
  { id: 'uk-1', name: 'Oliver Smith', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“I appreciate how simple everything looks.”', timeAgo: '2 days ago' },
  { id: 'uk-2', name: 'George Williams', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“I’ve had enough bad experiences online to stay careful.” 👀', timeAgo: '1 week ago' },
  { id: 'uk-3', name: 'Harry Brown', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“The app feels polished without looking too complicated.”', timeAgo: '3 weeks ago' },
  { id: 'uk-4', name: 'Jack Taylor', countryCode: 'GB', countryName: 'UK', rating: 4, text: '“I only joined after seeing people around me use it consistently.” 👌', timeAgo: '1 month ago' },
  { id: 'uk-5', name: 'Thomas Davies', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“The navigation feels natural.”', timeAgo: '2 months ago' },
  { id: 'uk-6', name: 'Amelia Wilson', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“I honestly expected support to disappear after registration.” 😅', timeAgo: '3 months ago' },
  { id: 'uk-7', name: 'Isla Johnson', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“The transaction process feels smooth every time.”', timeAgo: '4 months ago' },
  { id: 'uk-8', name: 'Sophie Walker', countryCode: 'GB', countryName: 'UK', rating: 4, text: '“The app actually looks maintained.”', timeAgo: '5 months ago' },
  { id: 'uk-9', name: 'Freya Thompson', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“I like how beginner friendly the interface feels.” 👍', timeAgo: '6 months ago' },
  { id: 'uk-10', name: 'Charlotte Evans', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“Still observing quietly before I fully trust it.”', timeAgo: '7 months ago' },
  { id: 'uk-11', name: 'Henry Roberts', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“Everything just works the way it should.” ✅', timeAgo: '8 months ago' },
  { id: 'uk-12', name: 'Edward Hughes', countryCode: 'GB', countryName: 'UK', rating: 4, text: '“I was prepared for stress but surprisingly didn’t get any.”', timeAgo: '9 months ago' },
  { id: 'uk-13', name: 'William Turner', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“The loading speed is one of the first things I noticed.” ⚡', timeAgo: '10 months ago' },
  { id: 'uk-14', name: 'Arthur Collins', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“I appreciate how organized the dashboard feels.”', timeAgo: '11 months ago' },
  { id: 'uk-15', name: 'Leo Morgan', countryCode: 'GB', countryName: 'UK', rating: 4, text: '“It’s refreshing to use something that isn’t confusing.”', timeAgo: '1 year ago' },
  { id: 'uk-16', name: 'Emily Scott', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“My cousin kept recommending it until I finally tried.” 😂', timeAgo: '1 year ago' },
  { id: 'uk-17', name: 'Jessica Parker', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“The app experience has been stable for me.”', timeAgo: '1 year ago' },
  { id: 'uk-18', name: 'Lucy Cooper', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“I’m not someone who rushes into platforms like this.”', timeAgo: '1 year ago' },
  { id: 'uk-19', name: 'Mia Richardson', countryCode: 'GB', countryName: 'UK', rating: 4, text: '“The support responses feel human and respectful.” 👏', timeAgo: '2 years ago' },
  { id: 'uk-20', name: 'Ella Bennett', countryCode: 'GB', countryName: 'UK', rating: 5, text: '“I like that the interface isn’t overcrowded.”', timeAgo: '2 years ago' },

  // Singapore (20)
  { id: 'sg-1', name: 'Ethan Tan', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“The onboarding process felt smoother than expected.” ✨', timeAgo: '2 days ago' },
  { id: 'sg-2', name: 'Ryan Lim', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“I still have trust issues generally, but so far things look okay.”', timeAgo: '1 week ago' },
  { id: 'sg-3', name: 'Daniel Wong', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“The app works perfectly fine on my device.” 📱', timeAgo: '3 weeks ago' },
  { id: 'sg-4', name: 'Marcus Lee', countryCode: 'SG', countryName: 'Singapore', rating: 4, text: '“I appreciate that everything is clearly arranged.”', timeAgo: '1 month ago' },
  { id: 'sg-5', name: 'Jason Koh', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“The design gives a premium feeling honestly.” 💎', timeAgo: '2 months ago' },
  { id: 'sg-6', name: 'Cheryl Ong', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“I joined quietly just to test things for myself.”', timeAgo: '3 months ago' },
  { id: 'sg-7', name: 'Rachel Tan', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“Everything has been straightforward so far.”', timeAgo: '4 months ago' },
  { id: 'sg-8', name: 'Grace Lim', countryCode: 'SG', countryName: 'Singapore', rating: 4, text: '“The transaction history section is easy to understand.” 📊', timeAgo: '5 months ago' },
  { id: 'sg-9', name: 'Amanda Chua', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“I expected hidden stress but didn’t really encounter any.”', timeAgo: '6 months ago' },
  { id: 'sg-10', name: 'Michelle Ng', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“The app feels very modern.”', timeAgo: '7 months ago' },
  { id: 'sg-11', name: 'Adrian Goh', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“So far the consistency has been decent.” 👍', timeAgo: '8 months ago' },
  { id: 'sg-12', name: 'Brandon Teo', countryCode: 'SG', countryName: 'Singapore', rating: 4, text: '“The support team answered my questions faster than expected.”', timeAgo: '9 months ago' },
  { id: 'sg-13', name: 'Nicole Seah', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“I’m still monitoring things carefully.” 👀', timeAgo: '10 months ago' },
  { id: 'sg-14', name: 'Vanessa Yeo', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“The platform feels easier than most others I’ve tested.”', timeAgo: '11 months ago' },
  { id: 'sg-15', name: 'Kevin Ang', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“I honestly didn’t expect to like the interface this much.” 🔥', timeAgo: '1 year ago' },
  { id: 'sg-16', name: 'Sophia Ho', countryCode: 'SG', countryName: 'Singapore', rating: 4, text: '“The mobile version feels smooth.”', timeAgo: '1 year ago' },
  { id: 'sg-17', name: 'Darren Loh', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“I appreciate how responsive everything feels.”', timeAgo: '1 year ago' },
  { id: 'sg-18', name: 'Jasmine Quek', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“It’s one of the cleaner dashboards I’ve seen.” ✨', timeAgo: '1 year ago' },
  { id: 'sg-19', name: 'Terence Yap', countryCode: 'SG', countryName: 'Singapore', rating: 4, text: '“I’ve had no issues navigating around the app.”', timeAgo: '2 years ago' },
  { id: 'sg-20', name: 'Clarissa Toh', countryCode: 'SG', countryName: 'Singapore', rating: 5, text: '“The simplicity makes a big difference honestly.”', timeAgo: '2 years ago' },

  // China (20)
  { id: 'cn-1', name: 'Li Wei', countryCode: 'CN', countryName: 'China', rating: 5, text: '“I joined because my friend wouldn’t stop talking about it.” 😂', timeAgo: '2 days ago' },
  { id: 'cn-2', name: 'Wang Jun', countryCode: 'CN', countryName: 'China', rating: 5, text: '“The experience has been surprisingly comfortable.”', timeAgo: '1 week ago' },
  { id: 'cn-3', name: 'Chen Hao', countryCode: 'CN', countryName: 'China', rating: 5, text: '“The app doesn’t feel stressful to use.” 😌', timeAgo: '3 weeks ago' },
  { id: 'cn-4', name: 'Zhang Lei', countryCode: 'CN', countryName: 'China', rating: 4, text: '“The support team communicates clearly.”', timeAgo: '1 month ago' },
  { id: 'cn-5', name: 'Liu Yang', countryCode: 'CN', countryName: 'China', rating: 5, text: '“I’m still taking things slowly.”', timeAgo: '2 months ago' },
  { id: 'cn-6', name: 'Mei Lin', countryCode: 'CN', countryName: 'China', rating: 5, text: '“Everything looks properly organized.” 👌', timeAgo: '3 months ago' },
  { id: 'cn-7', name: 'Xiao Chen', countryCode: 'CN', countryName: 'China', rating: 5, text: '“The app performance has been consistent.”', timeAgo: '4 months ago' },
  { id: 'cn-8', name: 'Lin Yue', countryCode: 'CN', countryName: 'China', rating: 4, text: '“I appreciate how smooth the verification process was.” ✅', timeAgo: '5 months ago' },
  { id: 'cn-9', name: 'Wang Fang', countryCode: 'CN', countryName: 'China', rating: 5, text: '“I honestly expected complications during withdrawal.” 💸', timeAgo: '6 months ago' },
  { id: 'cn-10', name: 'Zhao Min', countryCode: 'CN', countryName: 'China', rating: 5, text: '“The design feels intentional.”', timeAgo: '7 months ago' },
  { id: 'cn-11', name: 'Sun Tao', countryCode: 'CN', countryName: 'China', rating: 5, text: '“It’s easy to understand where everything is.”', timeAgo: '8 months ago' },
  { id: 'cn-12', name: 'Guo Jian', countryCode: 'CN', countryName: 'China', rating: 5, text: '“The dashboard makes monitoring simple.” 📊', timeAgo: '9 months ago' },
  { id: 'cn-13', name: 'Xu Ming', countryCode: 'CN', countryName: 'China', rating: 4, text: '“I tested it randomly and ended up staying longer than planned.”', timeAgo: '10 months ago' },
  { id: 'cn-14', name: 'Huang Bo', countryCode: 'CN', countryName: 'China', rating: 5, text: '“The support experience was much better than expected.” 👍', timeAgo: '11 months ago' },
  { id: 'cn-15', name: 'Zhou Kai', countryCode: 'CN', countryName: 'China', rating: 5, text: '“I’m naturally skeptical so I still observe carefully.”', timeAgo: '1 year ago' },
  { id: 'cn-16', name: 'Yang Mei', countryCode: 'CN', countryName: 'China', rating: 5, text: '“The app feels reliable so far.”', timeAgo: '1 year ago' },
  { id: 'cn-17', name: 'Tang Li', countryCode: 'CN', countryName: 'China', rating: 4, text: '“I appreciate how easy it is to use daily.” ✨', timeAgo: '1 year ago' },
  { id: 'cn-18', name: 'Feng Yu', countryCode: 'CN', countryName: 'China', rating: 5, text: '“Everything responds quickly without lag.”', timeAgo: '1 year ago' },
  { id: 'cn-19', name: 'Jin Hao', countryCode: 'CN', countryName: 'China', rating: 5, text: '“The interface feels professional.” 💼', timeAgo: '2 years ago' },
  { id: 'cn-20', name: 'Cai Wen', countryCode: 'CN', countryName: 'China', rating: 5, text: '“I joined after hearing several recommendations.”', timeAgo: '2 years ago' },

  // Tanzania (20)
  { id: 'tz-1', name: 'John Mwakyusa', countryCode: 'TZ', countryName: 'Tanzania', rating: 5, text: '“The experience has been smooth from the start.”', timeAgo: '2 days ago' },
  { id: 'tz-2', name: 'Peter Msuya', countryCode: 'TZ', countryName: 'Tanzania', rating: 5, text: '“I like how lightweight the app feels.” 📱', timeAgo: '1 week ago' },
  { id: 'tz-3', name: 'David Mrema', countryCode: 'TZ', countryName: 'Tanzania', rating: 5, text: '“The registration process took almost no time.”', timeAgo: '3 weeks ago' },
  { id: 'tz-4', name: 'Joseph Mallya', countryCode: 'TZ', countryName: 'Tanzania', rating: 4, text: '“I’m impressed but still careful.” 👀', timeAgo: '1 month ago' },
  { id: 'tz-5', name: 'Emmanuel Nyerere', countryCode: 'TZ', countryName: 'Tanzania', rating: 5, text: '“The support quality stood out to me.”', timeAgo: '2 months ago' },
  { id: 'tz-6', name: 'Neema Joseph', countryCode: 'TZ', countryName: 'Tanzania', rating: 5, text: '“The layout makes sense immediately.”', timeAgo: '3 months ago' },
  { id: 'tz-7', name: 'Asha Mwakipesile', countryCode: 'TZ', countryName: 'Tanzania', rating: 5, text: '“I expected confusion but didn’t experience any.” 😅', timeAgo: '4 months ago' },
  { id: 'tz-8', name: 'Rehema Bakari', countryCode: 'TZ', countryName: 'Tanzania', rating: 4, text: '“The app gives a trustworthy first impression.”', timeAgo: '5 months ago' },
  { id: 'tz-9', name: 'Zawadi Mushi', countryCode: 'TZ', countryName: 'Tanzania', rating: 5, text: '“Everything about the experience feels polished.” ✨', timeAgo: '6 months ago' },
  { id: 'tz-10', name: 'Grace Mollel', countryCode: 'TZ', countryName: 'Tanzania', rating: 5, text: '“The navigation is very straightforward.”', timeAgo: '7 months ago' },
  { id: 'tz-11', name: 'Michael Mosha', countryCode: 'TZ', countryName: 'Tanzania', rating: 5, text: '“I’ve had a calm experience using it so far.” 😌', timeAgo: '8 months ago' },
  { id: 'tz-12', name: 'Brian Mariki', countryCode: 'TZ', countryName: 'Tanzania', rating: 4, text: '“The interface is surprisingly beginner friendly.”', timeAgo: '9 months ago' },
  { id: 'tz-13', name: 'Kelvin Mtema', countryCode: 'TZ', countryName: 'Tanzania', rating: 4, text: '“The app doesn’t overload you with unnecessary things.”', timeAgo: '10 months ago' },
  { id: 'tz-14', name: 'Esther Kilango', countryCode: 'TZ', countryName: 'Tanzania', rating: 5, text: '“I appreciate how quickly transactions update.” ⚡', timeAgo: '11 months ago' },
  { id: 'tz-15', name: 'Glory Mtei', countryCode: 'TZ', countryName: 'Tanzania', rating: 5, text: '“I honestly thought the hype was exaggerated at first.”', timeAgo: '1 year ago' },
  { id: 'tz-16', name: 'Anna Mwakalebela', countryCode: 'TZ', countryName: 'Tanzania', rating: 5, text: '“The customer support was patient with me.” 👏', timeAgo: '1 year ago' },
  { id: 'tz-17', name: 'Victor Chuwa', countryCode: 'TZ', countryName: 'Tanzania', rating: 4, text: '“The app feels stable during use.”', timeAgo: '1 year ago' },
  { id: 'tz-18', name: 'Happiness Mgaya', countryCode: 'TZ', countryName: 'Tanzania', rating: 5, text: '“I’ve seen worse platforms honestly.”', timeAgo: '1 year ago' },
  { id: 'tz-19', name: 'Frank Mbise', countryCode: 'TZ', countryName: 'Tanzania', rating: 5, text: '“The clean design is one of my favorite things.” ✨', timeAgo: '2 years ago' },
  { id: 'tz-20', name: 'Janeth Lyimo', countryCode: 'TZ', countryName: 'Tanzania', rating: 5, text: '“The experience has been decent overall.”', timeAgo: '2 years ago' },

  // Uganda (20)
  { id: 'ug-1', name: 'Brian Kato', countryCode: 'UG', countryName: 'Uganda', rating: 5, text: '“I still observe before making bigger decisions.” 👀', timeAgo: '2 days ago' },
  { id: 'ug-2', name: 'Daniel Ssemanda', countryCode: 'UG', countryName: 'Uganda', rating: 5, text: '“Everything works smoothly on mobile.”', timeAgo: '1 week ago' },
  { id: 'ug-3', name: 'Michael Mugisha', countryCode: 'UG', countryName: 'Uganda', rating: 5, text: '“The app feels easier than expected.”', timeAgo: '3 weeks ago' },
  { id: 'ug-4', name: 'Isaac Okello', countryCode: 'UG', countryName: 'Uganda', rating: 4, text: '“I appreciate the simplicity of the dashboard.” 👍', timeAgo: '1 month ago' },
  { id: 'ug-5', name: 'David Byaruhanga', countryCode: 'UG', countryName: 'Uganda', rating: 5, text: '“The transaction flow is smooth every time.”', timeAgo: '2 months ago' },
  { id: 'ug-6', name: 'Sarah Namusoke', countryCode: 'UG', countryName: 'Uganda', rating: 5, text: '“I thought there would be hidden stress somewhere.” 😅', timeAgo: '3 months ago' },
  { id: 'ug-7', name: 'Gloria Nankunda', countryCode: 'UG', countryName: 'Uganda', rating: 5, text: '“The interface looks professionally done.”', timeAgo: '4 months ago' },
  { id: 'ug-8', name: 'Mercy Atim', countryCode: 'UG', countryName: 'Uganda', rating: 4, text: '“The app experience has been comfortable so far.”', timeAgo: '5 months ago' },
  { id: 'ug-9', name: 'Patricia Nalubega', countryCode: 'UG', countryName: 'Uganda', rating: 5, text: '“I’m waiting to see long-term consistency.” ⏳', timeAgo: '6 months ago' },
  { id: 'ug-10', name: 'Ruth Achieng', countryCode: 'UG', countryName: 'Uganda', rating: 5, text: '“The onboarding process was surprisingly easy.”', timeAgo: '7 months ago' },
  { id: 'ug-11', name: 'Joseph Tumusiime', countryCode: 'UG', countryName: 'Uganda', rating: 5, text: '“The support response speed impressed me.” ⚡', timeAgo: '8 months ago' },
  { id: 'ug-12', name: 'Paul Wasswa', countryCode: 'UG', countryName: 'Uganda', rating: 4, text: '“The platform feels user friendly.”', timeAgo: '9 months ago' },
  { id: 'ug-13', name: 'Ronald Ocen', countryCode: 'UG', countryName: 'Uganda', rating: 4, text: '“I’ve had a better experience than expected.” 🙂', timeAgo: '10 months ago' },
  { id: 'ug-14', name: 'Kevin Kakooza', countryCode: 'UG', countryName: 'Uganda', rating: 5, text: '“The app doesn’t feel cluttered.”', timeAgo: '11 months ago' },
  { id: 'ug-15', name: 'Esther Nakato', countryCode: 'UG', countryName: 'Uganda', rating: 5, text: '“Everything feels properly optimized.” 🔥', timeAgo: '1 year ago' },
  { id: 'ug-16', name: 'Sharon Akello', countryCode: 'UG', countryName: 'Uganda', rating: 5, text: '“The dashboard layout is clean.”', timeAgo: '1 year ago' },
  { id: 'ug-17', name: 'Emmanuel Ssenyonga', countryCode: 'UG', countryName: 'Uganda', rating: 4, text: '“I’m still cautious naturally.”', timeAgo: '1 year ago' },
  { id: 'ug-18', name: 'Doreen Nantongo', countryCode: 'UG', countryName: 'Uganda', rating: 5, text: '“The experience has been smooth enough for me.” 👍', timeAgo: '1 year ago' },
  { id: 'ug-19', name: 'Ivan Balikuddembe', countryCode: 'UG', countryName: 'Uganda', rating: 5, text: '“The support team actually listens.”', timeAgo: '2 years ago' },
  { id: 'ug-20', name: 'Peace Kemigisa', countryCode: 'UG', countryName: 'Uganda', rating: 5, text: '“The app performance has been reliable.” 📱', timeAgo: '2 years ago' },

  // Ghana (20)
  { id: 'gh-1', name: 'Kwame Mensah', countryCode: 'GH', countryName: 'Ghana', rating: 5, text: '“I honestly expected the withdrawals to be difficult.” 💸', timeAgo: '2 days ago' },
  { id: 'gh-2', name: 'Abena Osei', countryCode: 'GH', countryName: 'Ghana', rating: 5, text: '“The experience is very straightforward.”', timeAgo: '1 week ago' },
  { id: 'gh-3', name: 'Kofi Appiah', countryCode: 'GH', countryName: 'Ghana', rating: 5, text: '“I joined because I saw a close friend using it.”', timeAgo: '3 weeks ago' },
  { id: 'gh-4', name: 'Ama Boateng', countryCode: 'GH', countryName: 'Ghana', rating: 4, text: '“The support team is actually helpful.” 👏', timeAgo: '1 month ago' },
  { id: 'gh-5', name: 'Yaw Asante', countryCode: 'GH', countryName: 'Ghana', rating: 5, text: '“I’m still observing but I like what I see.”', timeAgo: '2 months ago' },
  { id: 'gh-6', name: 'Ekow Baidoo', countryCode: 'GH', countryName: 'Ghana', rating: 5, text: '“The app feels much smoother than I thought.” ✨', timeAgo: '3 months ago' },
  { id: 'gh-7', name: 'Akua Addo', countryCode: 'GH', countryName: 'Ghana', rating: 5, text: '“Everything looks clean and well organized.”', timeAgo: '4 months ago' },
  { id: 'gh-8', name: 'Kwesi Arthur', countryCode: 'GH', countryName: 'Ghana', rating: 4, text: '“The dashboard makes it easy to track progress.”', timeAgo: '5 months ago' },
  { id: 'gh-9', name: 'Efua Forson', countryCode: 'GH', countryName: 'Ghana', rating: 5, text: '“I’ve had a very calm experience so far.” 😌', timeAgo: '6 months ago' },
  { id: 'gh-10', name: 'Nana Yaw', countryCode: 'GH', countryName: 'Ghana', rating: 5, text: '“The verification was faster than expected.” ✅', timeAgo: '7 months ago' },
  { id: 'gh-11', name: 'Afua Serwaa', countryCode: 'GH', countryName: 'Ghana', rating: 5, text: '“The interface flows very well.”', timeAgo: '8 months ago' },
  { id: 'gh-12', name: 'Kojo Antwi', countryCode: 'GH', countryName: 'Ghana', rating: 5, text: '“I appreciate the lack of unnecessary clutter.”', timeAgo: '9 months ago' },
  { id: 'gh-13', name: 'Mavis Agyeman', countryCode: 'GH', countryName: 'Ghana', rating: 4, text: '“The app performance has been stable.” 📱', timeAgo: '10 months ago' },
  { id: 'gh-14', name: 'Bright Ofori', countryCode: 'GH', countryName: 'Ghana', rating: 5, text: '“I honestly thought it would be more complicated.”', timeAgo: '11 months ago' },
  { id: 'gh-15', name: 'Adjoa Sarfo', countryCode: 'GH', countryName: 'Ghana', rating: 5, text: '“The customer service actually responds on time.” ⚡', timeAgo: '1 year ago' },
  { id: 'gh-16', name: 'Paa Kwesi', countryCode: 'GH', countryName: 'Ghana', rating: 5, text: '“The experience feels professional.”', timeAgo: '1 year ago' },
  { id: 'gh-17', name: 'Lydia Forson', countryCode: 'GH', countryName: 'Ghana', rating: 4, text: '“I’m happy with how easy it is to navigate.” 👍', timeAgo: '1 year ago' },
  { id: 'gh-18', name: 'Samuel Owusu', countryCode: 'GH', countryName: 'Ghana', rating: 5, text: '“Everything responded correctly during signup.”', timeAgo: '1 year ago' },
  { id: 'gh-19', name: 'Bernice Addo', countryCode: 'GH', countryName: 'Ghana', rating: 5, text: '“The app feels reliable for daily use.”', timeAgo: '2 years ago' },
  { id: 'gh-20', name: 'George Boateng', countryCode: 'GH', countryName: 'Ghana', rating: 5, text: '“I’m glad I gave it a try finally.” 🙂', timeAgo: '2 years ago' },

  // Nigeria (20)
  { id: 'ng-1', name: 'Ayo Adebayo', countryCode: 'NG', countryName: 'Nigeria', rating: 5, text: 'The ROI is consistent and the interface is very professional.', timeAgo: '2 days ago' },
  { id: 'ng-2', name: 'Oluwaseun Bakare', countryCode: 'NG', countryName: 'Nigeria', rating: 5, text: 'Tavari Wave has transformed how I manage my digital assets.', timeAgo: '1 week ago' },
  { id: 'ng-3', name: 'Chidi Okoro', countryCode: 'NG', countryName: 'Nigeria', rating: 5, text: 'Fast withdrawals and great support. The premium plan is a game changer.', timeAgo: '3 weeks ago' },
  { id: 'ng-4', name: 'Amaka Eze', countryCode: 'NG', countryName: 'Nigeria', rating: 4, text: 'Seamless experience from signup to my first harvest.', timeAgo: '1 month ago' },
  { id: 'ng-5', name: 'Babajide Sowore', countryCode: 'NG', countryName: 'Nigeria', rating: 5, text: 'The security protocols give me peace of mind.', timeAgo: '2 months ago' },
  { id: 'ng-6', name: 'Funke Akindele', countryCode: 'NG', countryName: 'Nigeria', rating: 5, text: 'Impressive yields and very transparent operations.', timeAgo: '3 months ago' },
  { id: 'ng-7', name: 'Ibrahim Musa', countryCode: 'NG', countryName: 'Nigeria', rating: 5, text: 'Good platform for institutional grade returns.', timeAgo: '4 months ago' },
  { id: 'ng-8', name: 'Nneka Johnson', countryCode: 'NG', countryName: 'Nigeria', rating: 4, text: 'Tavari is the future of wealth management.', timeAgo: '5 months ago' },
  { id: 'ng-9', name: 'Tunde Afolayan', countryCode: 'NG', countryName: 'Nigeria', rating: 5, text: 'The regular plan is perfect for beginners.', timeAgo: '6 months ago' },
  { id: 'ng-10', name: 'Zainab Bello', countryCode: 'NG', countryName: 'Nigeria', rating: 5, text: 'Exceptional service and very rewarding ROI clusters.', timeAgo: '7 months ago' },
  { id: 'ng-11', name: 'Emeka Nwosu', countryCode: 'NG', countryName: 'Nigeria', rating: 5, text: 'Finally a platform that delivers on its promises.', timeAgo: '8 months ago' },
  { id: 'ng-12', name: 'Blessing Udoh', countryCode: 'NG', countryName: 'Nigeria', rating: 4, text: 'The user experience is premium. Everything works.', timeAgo: '9 months ago' },
  { id: 'ng-13', name: 'Segun Arinze', countryCode: 'NG', countryName: 'Nigeria', rating: 5, text: 'Reliable and secure node processes.', timeAgo: '10 months ago' },
  { id: 'ng-14', name: 'Yinka Shonibare', countryCode: 'NG', countryName: 'Nigeria', rating: 5, text: 'Great for long term wealth building.', timeAgo: '11 months ago' },
  { id: 'ng-15', name: 'Damilola Taylor', countryCode: 'NG', countryName: 'Nigeria', rating: 4, text: 'Excellent support team and guided onboarding.', timeAgo: '1 year ago' },
  { id: 'ng-16', name: 'Kelechi Iheanacho', countryCode: 'NG', countryName: 'Nigeria', rating: 5, text: 'The neural trading engine is truly next-gen.', timeAgo: '1 year ago' },
  { id: 'ng-17', name: 'Oyinade Coker', countryCode: 'NG', countryName: 'Nigeria', rating: 5, text: 'Consistent daily earnings. Best decision.', timeAgo: '1 year ago' },
  { id: 'ng-18', name: 'Femi Otedola', countryCode: 'NG', countryName: 'Nigeria', rating: 5, text: 'Elite interface for elite investors. Highly recommend.', timeAgo: '1 year ago' },
  { id: 'ng-19', name: 'Aliko Dangote', countryCode: 'NG', countryName: 'Nigeria', rating: 5, text: 'Setting new standards in asset management.', timeAgo: '2 years ago' },
  { id: 'ng-20', name: 'Genevieve Nnaji', countryCode: 'NG', countryName: 'Nigeria', rating: 5, text: 'Elite security and elite performance. Best in market.', timeAgo: '2 years ago' },

  // Australia (20)
  { id: 'au-1', name: 'Lachlan Murdoch', countryCode: 'AU', countryName: 'Australia', rating: 5, text: 'Reliable node execution and transparent reporting.', timeAgo: '2 days ago' },
  { id: 'au-2', name: 'Gina Rinehart', countryCode: 'AU', countryName: 'Australia', rating: 5, text: 'The neural clusters provide a unique advantage.', timeAgo: '1 week ago' },
  { id: 'au-3', name: 'Andrew Forrest', countryCode: 'AU', countryName: 'Australia', rating: 5, text: 'Sophisticated platform with impressive yield.', timeAgo: '3 weeks ago' },
  { id: 'au-4', name: 'Harry Triguboff', countryCode: 'AU', countryName: 'Australia', rating: 4, text: 'Premium experience throughout. Highly effective.', timeAgo: '1 month ago' },
  { id: 'au-5', name: 'Frank Lowy', countryCode: 'AU', countryName: 'Australia', rating: 5, text: 'Institutional grade security meets modern tech.', timeAgo: '2 months ago' },
  { id: 'au-6', name: 'Anthony Pratt', countryCode: 'AU', countryName: 'Australia', rating: 5, text: 'Seamless asset orchestration. My top choice.', timeAgo: '3 months ago' },
  { id: 'au-7', name: 'Mike Cannon-Brookes', countryCode: 'AU', countryName: 'Australia', rating: 5, text: 'The daily ROI updates keep you engaged.', timeAgo: '4 months ago' },
  { id: 'au-8', name: 'Scott Farquhar', countryCode: 'AU', countryName: 'Australia', rating: 4, text: 'Tavari Wave delivers on its promise of excellence.', timeAgo: '5 months ago' },
  { id: 'au-9', name: 'Clive Palmer', countryCode: 'AU', countryName: 'Australia', rating: 5, text: 'The regular node activation was easy.', timeAgo: '6 months ago' },
  { id: 'au-10', name: 'James Packer', countryCode: 'AU', countryName: 'Australia', rating: 5, text: 'Superior tech and superior support.', timeAgo: '7 months ago' },
  { id: 'au-11', name: 'Cate Blanchett', countryCode: 'AU', countryName: 'Australia', rating: 5, text: 'Fast withdrawals and great support.', timeAgo: '8 months ago' },
  { id: 'au-12', name: 'Hugh Jackman', countryCode: 'AU', countryName: 'Australia', rating: 4, text: 'Seamless experience from signup.', timeAgo: '9 months ago' },
  { id: 'au-13', name: 'Nicole Kidman', countryCode: 'AU', countryName: 'Australia', rating: 4, text: 'The security protocols give me peace.', timeAgo: '10 months ago' },
  { id: 'au-14', name: 'Margot Robbie', countryCode: 'AU', countryName: 'Australia', rating: 5, text: 'Impressive yields and transparent ops.', timeAgo: '11 months ago' },
  { id: 'au-15', name: 'Chris Hemsworth', countryCode: 'AU', countryName: 'Australia', rating: 5, text: 'Good platform for institutional grade.', timeAgo: '1 year ago' },
  { id: 'au-16', name: 'Kylie Minogue', countryCode: 'AU', countryName: 'Australia', rating: 5, text: 'Tavari is the future of wealth.', timeAgo: '1 year ago' },
  { id: 'au-17', name: 'Steve Smith', countryCode: 'AU', countryName: 'Australia', rating: 4, text: 'The regular plan is perfect.', timeAgo: '1 year ago' },
  { id: 'au-18', name: 'Shane Warne', countryCode: 'AU', countryName: 'Australia', rating: 5, text: 'Exceptional service and rewarding.', timeAgo: '1 year ago' },
  { id: 'au-19', name: 'Ian Thorpe', countryCode: 'AU', countryName: 'Australia', rating: 5, text: 'Finally a platform that delivers.', timeAgo: '2 years ago' },
  { id: 'au-20', name: 'Cathy Freeman', countryCode: 'AU', countryName: 'Australia', rating: 5, text: 'The user experience is premium.', timeAgo: '2 years ago' },

  // South Africa (20)
  { id: 'za-1', name: 'Elon Musk', countryCode: 'ZA', countryName: 'South Africa', rating: 5, text: 'Reliable node execution and transparent reporting.', timeAgo: '2 days ago' },
  { id: 'za-2', name: 'Patrice Motsepe', countryCode: 'ZA', countryName: 'South Africa', rating: 5, text: 'The neural clusters provide a unique advantage.', timeAgo: '1 week ago' },
  { id: 'za-3', name: 'Johann Rupert', countryCode: 'ZA', countryName: 'South Africa', rating: 5, text: 'Sophisticated platform with impressive yield.', timeAgo: '3 weeks ago' },
  { id: 'za-4', name: 'Nicky Oppenheimer', countryCode: 'ZA', countryName: 'South Africa', rating: 4, text: 'Premium experience throughout. Highly effective.', timeAgo: '1 month ago' },
  { id: 'za-5', name: 'Cyril Ramaphosa', countryCode: 'ZA', countryName: 'South Africa', rating: 5, text: 'Institutional grade security meets modern tech.', timeAgo: '2 months ago' },
  { id: 'za-6', name: 'Trevor Noah', countryCode: 'ZA', countryName: 'South Africa', rating: 5, text: 'Seamless asset orchestration. My top choice.', timeAgo: '3 months ago' },
  { id: 'za-7', name: 'Charlize Theron', countryCode: 'ZA', countryName: 'South Africa', rating: 5, text: 'The daily ROI updates keep you engaged.', timeAgo: '4 months ago' },
  { id: 'za-8', name: 'Black Coffee', countryCode: 'ZA', countryName: 'South Africa', rating: 4, text: 'Tavari Wave delivers on its promise of excellence.', timeAgo: '5 months ago' },
  { id: 'za-9', name: 'Siya Kolisi', countryCode: 'ZA', countryName: 'South Africa', rating: 5, text: 'The regular node activation was easy.', timeAgo: '6 months ago' },
  { id: 'za-10', name: 'Caster Semenya', countryCode: 'ZA', countryName: 'South Africa', rating: 5, text: 'Superior tech and superior support.', timeAgo: '7 months ago' },
  { id: 'za-11', name: 'Thabo Mbeki', countryCode: 'ZA', countryName: 'South Africa', rating: 5, text: 'Fast withdrawals and great support.', timeAgo: '8 months ago' },
  { id: 'za-12', name: 'Desmond Tutu', countryCode: 'ZA', countryName: 'South Africa', rating: 4, text: 'Seamless experience from signup.', timeAgo: '9 months ago' },
  { id: 'za-13', name: 'Nelson Mandela', countryCode: 'ZA', countryName: 'South Africa', rating: 4, text: 'The security protocols give me peace.', timeAgo: '10 months ago' },
  { id: 'za-14', name: 'Winnie Mandela', countryCode: 'ZA', countryName: 'South Africa', rating: 5, text: 'Impressive yields and transparent ops.', timeAgo: '11 months ago' },
  { id: 'za-15', name: 'Zozibini Tunzi', countryCode: 'ZA', countryName: 'South Africa', rating: 5, text: 'Good platform for institutional grade.', timeAgo: '1 year ago' },
  { id: 'za-16', name: 'Nomzamo Mbatha', countryCode: 'ZA', countryName: 'South Africa', rating: 5, text: 'Tavari is the future of wealth.', timeAgo: '1 year ago' },
  { id: 'za-17', name: 'Bonang Matheba', countryCode: 'ZA', countryName: 'South Africa', rating: 4, text: 'The regular plan is perfect.', timeAgo: '1 year ago' },
  { id: 'za-18', name: 'Sizwe Dhlomo', countryCode: 'ZA', countryName: 'South Africa', rating: 5, text: 'Exceptional service and rewarding.', timeAgo: '1 year ago' },
  { id: 'za-19', name: 'Kabelo Mabalane', countryCode: 'ZA', countryName: 'South Africa', rating: 5, text: 'Finally a platform that delivers.', timeAgo: '2 years ago' },
  { id: 'za-20', name: 'Refilwe Ledwaba', countryCode: 'ZA', countryName: 'South Africa', rating: 5, text: 'The user experience is premium.', timeAgo: '2 years ago' },

  // Ivory Coast (20)
  { id: 'ci-1', name: 'Alassane Ouattara', countryCode: 'CI', countryName: 'Ivory Coast', rating: 5, text: 'Reliable node execution and transparent reporting.', timeAgo: '2 days ago' },
  { id: 'ci-2', name: 'Didier Drogba', countryCode: 'CI', countryName: 'Ivory Coast', rating: 5, text: 'The neural clusters provide a unique advantage.', timeAgo: '1 week ago' },
  { id: 'ci-3', name: 'Yaya Touré', countryCode: 'CI', countryName: 'Ivory Coast', rating: 5, text: 'Sophisticated platform with impressive yield.', timeAgo: '3 weeks ago' },
  { id: 'ci-4', name: 'Alpha Blondy', countryCode: 'CI', countryName: 'Ivory Coast', rating: 4, text: 'Premium experience throughout. Highly effective.', timeAgo: '1 month ago' },
  { id: 'ci-5', name: 'Magic System', countryCode: 'CI', countryName: 'Ivory Coast', rating: 5, text: 'Institutional grade security meets modern tech.', timeAgo: '2 months ago' },
  { id: 'ci-6', name: 'Gervinho', countryCode: 'CI', countryName: 'Ivory Coast', rating: 5, text: 'Seamless asset orchestration. My top choice.', timeAgo: '3 months ago' },
  { id: 'ci-7', name: 'Kolo Touré', countryCode: 'CI', countryName: 'Ivory Coast', rating: 5, text: 'The daily ROI updates keep you engaged.', timeAgo: '4 months ago' },
  { id: 'ci-8', name: 'Salomon Kalou', countryCode: 'CI', countryName: 'Ivory Coast', rating: 4, text: 'Tavari Wave delivers on its promise of excellence.', timeAgo: '5 months ago' },
  { id: 'ci-9', name: 'Wilfried Zaha', countryCode: 'CI', countryName: 'Ivory Coast', rating: 5, text: 'The regular node activation was easy.', timeAgo: '6 months ago' },
  { id: 'ci-10', name: 'Franck Kessié', countryCode: 'CI', countryName: 'Ivory Coast', rating: 5, text: 'Superior tech and superior support.', timeAgo: '7 months ago' },
  { id: 'ci-11', name: 'Max Gradel', countryCode: 'CI', countryName: 'Ivory Coast', rating: 5, text: 'Fast withdrawals and great support.', timeAgo: '8 months ago' },
  { id: 'ci-12', name: 'Serge Aurier', countryCode: 'CI', countryName: 'Ivory Coast', rating: 4, text: 'Seamless experience from signup.', timeAgo: '9 months ago' },
  { id: 'ci-13', name: 'Sébastien Haller', countryCode: 'CI', countryName: 'Ivory Coast', rating: 4, text: 'The security protocols give me peace.', timeAgo: '10 months ago' },
  { id: 'ci-14', name: 'Nicolas Pépé', countryCode: 'CI', countryName: 'Ivory Coast', rating: 5, text: 'Impressive yields and transparent ops.', timeAgo: '11 months ago' },
  { id: 'ci-15', name: 'Ahmed Bakayoko', countryCode: 'CI', countryName: 'Ivory Coast', rating: 5, text: 'Good platform for institutional grade.', timeAgo: '1 year ago' },
  { id: 'ci-16', name: 'Hamid Bakayoko', countryCode: 'CI', countryName: 'Ivory Coast', rating: 5, text: 'Tavari is the future of wealth.', timeAgo: '1 year ago' },
  { id: 'ci-17', name: 'Charles Kader Gooré', countryCode: 'CI', countryName: 'Ivory Coast', rating: 4, text: 'The regular plan is perfect.', timeAgo: '1 year ago' },
  { id: 'ci-18', name: 'Jean-Louis Billon', countryCode: 'CI', countryName: 'Ivory Coast', rating: 5, text: 'Exceptional service and rewarding.', timeAgo: '1 year ago' },
  { id: 'ci-19', name: 'Tidjane Thiam', countryCode: 'CI', countryName: 'Ivory Coast', rating: 5, text: 'Finally a platform that delivers.', timeAgo: '2 years ago' },
  { id: 'ci-20', name: 'Fabrice Sawegnon', countryCode: 'CI', countryName: 'Ivory Coast', rating: 5, text: 'The user experience is premium.', timeAgo: '2 years ago' },

  // Kenya (20)
  { id: 'ke-1', name: 'Uhuru Kenyatta', countryCode: 'KE', countryName: 'Kenya', rating: 5, text: 'Reliable node execution and transparent reporting.', timeAgo: '2 days ago' },
  { id: 'ke-2', name: 'Raila Odinga', countryCode: 'KE', countryName: 'Kenya', rating: 5, text: 'The neural clusters provide a unique advantage.', timeAgo: '1 week ago' },
  { id: 'ke-3', name: 'William Ruto', countryCode: 'KE', countryName: 'Kenya', rating: 5, text: 'Sophisticated platform with impressive yield.', timeAgo: '3 weeks ago' },
  { id: 'ke-4', name: 'Eliud Kipchoge', countryCode: 'KE', countryName: 'Kenya', rating: 4, text: 'Premium experience throughout. Highly effective.', timeAgo: '1 month ago' },
  { id: 'ke-5', name: 'Lupita Nyong\'o', countryCode: 'KE', countryName: 'Kenya', rating: 5, text: 'Institutional grade security meets modern tech.', timeAgo: '2 months ago' },
  { id: 'ke-6', name: 'Sauti Sol', countryCode: 'KE', countryName: 'Kenya', rating: 5, text: 'Seamless asset orchestration. My top choice.', timeAgo: '3 months ago' },
  { id: 'ke-7', name: 'Victor Wanyama', countryCode: 'KE', countryName: 'Kenya', rating: 5, text: 'The daily ROI updates keep you engaged.', timeAgo: '4 months ago' },
  { id: 'ke-8', name: 'Michael Olunga', countryCode: 'KE', countryName: 'Kenya', rating: 4, text: 'Tavari Wave delivers on its promise of excellence.', timeAgo: '5 months ago' },
  { id: 'ke-9', name: 'David Rudisha', countryCode: 'KE', countryName: 'Kenya', rating: 5, text: 'The regular node activation was easy.', timeAgo: '6 months ago' },
  { id: 'ke-10', name: 'Faith Kipyegon', countryCode: 'KE', countryName: 'Kenya', rating: 5, text: 'Superior tech and superior support.', timeAgo: '7 months ago' },
  { id: 'ke-11', name: 'Jeff Koinange', countryCode: 'KE', countryName: 'Kenya', rating: 5, text: 'Fast withdrawals and great support.', timeAgo: '8 months ago' },
  { id: 'ke-12', name: 'Victoria Rubadiri', countryCode: 'KE', countryName: 'Kenya', rating: 4, text: 'Seamless experience from signup.', timeAgo: '9 months ago' },
  { id: 'ke-13', name: 'Maina Kageni', countryCode: 'KE', countryName: 'Kenya', rating: 4, text: 'The security protocols give me peace.', timeAgo: '10 months ago' },
  { id: 'ke-14', name: 'Caroline Mutoko', countryCode: 'KE', countryName: 'Kenya', rating: 5, text: 'Impressive yields and transparent ops.', timeAgo: '11 months ago' },
  { id: 'ke-15', name: 'Daniel Ndambuki', countryCode: 'KE', countryName: 'Kenya', rating: 5, text: 'Good platform for institutional grade.', timeAgo: '1 year ago' },
  { id: 'ke-16', name: 'Eric Omondi', countryCode: 'KE', countryName: 'Kenya', rating: 5, text: 'Tavari is the future of wealth.', timeAgo: '1 year ago' },
  { id: 'ke-17', name: 'Janet Mbugua', countryCode: 'KE', countryName: 'Kenya', rating: 4, text: 'The regular plan is perfect.', timeAgo: '1 year ago' },
  { id: 'ke-18', name: 'Larry Madowo', countryCode: 'KE', countryName: 'Kenya', rating: 5, text: 'Exceptional service and rewarding.', timeAgo: '1 year ago' },
  { id: 'ke-19', name: 'James Mwangi', countryCode: 'KE', countryName: 'Kenya', rating: 5, text: 'Finally a platform that delivers.', timeAgo: '2 years ago' },
  { id: 'ke-20', name: 'Tabitha Karanja', countryCode: 'KE', countryName: 'Kenya', rating: 5, text: 'The user experience is premium.', timeAgo: '2 years ago' },

  // Zimbabwe (20)
  { id: 'zw-1', name: 'Emmerson Mnangagwa', countryCode: 'ZW', countryName: 'Zimbabwe', rating: 5, text: 'Reliable node execution and transparent reporting.', timeAgo: '2 days ago' },
  { id: 'zw-2', name: 'Nelson Chamisa', countryCode: 'ZW', countryName: 'Zimbabwe', rating: 5, text: 'The neural clusters provide a unique advantage.', timeAgo: '1 week ago' },
  { id: 'zw-3', name: 'Strive Masiyiwa', countryCode: 'ZW', countryName: 'Zimbabwe', rating: 5, text: 'Sophisticated platform with impressive yield.', timeAgo: '3 weeks ago' },
  { id: 'zw-4', name: 'Shingai Mutasa', countryCode: 'ZW', countryName: 'Zimbabwe', rating: 4, text: 'Premium experience throughout. Highly effective.', timeAgo: '1 month ago' },
  { id: 'zw-5', name: 'Divine Ndhlukula', countryCode: 'ZW', countryName: 'Zimbabwe', rating: 5, text: 'Institutional grade security meets modern tech.', timeAgo: '2 months ago' },
  { id: 'zw-6', name: 'Oliver Mtukudzi', countryCode: 'ZW', countryName: 'Zimbabwe', rating: 5, text: 'Seamless asset orchestration. My top choice.', timeAgo: '3 months ago' },
  { id: 'zw-7', name: 'Thomas Mapfumo', countryCode: 'ZW', countryName: 'Zimbabwe', rating: 5, text: 'The daily ROI updates keep you engaged.', timeAgo: '4 months ago' },
  { id: 'zw-8', name: 'Jah Prayzah', countryCode: 'ZW', countryName: 'Zimbabwe', rating: 4, text: 'Tavari Wave delivers on its promise of excellence.', timeAgo: '5 months ago' },
  { id: 'zw-9', name: 'Winky D', countryCode: 'ZW', countryName: 'Zimbabwe', rating: 5, text: 'The regular node activation was easy.', timeAgo: '6 months ago' },
  { id: 'zw-10', name: 'Kirsty Coventry', countryCode: 'ZW', countryName: 'Zimbabwe', rating: 5, text: 'Superior tech and superior support.', timeAgo: '7 months ago' },
  { id: 'zw-11', name: 'Cara Black', countryCode: 'ZW', countryName: 'Zimbabwe', rating: 5, text: 'Fast withdrawals and great support.', timeAgo: '8 months ago' },
  { id: 'zw-12', name: 'Peter Ndlovu', countryCode: 'ZW', countryName: 'Zimbabwe', rating: 4, text: 'Seamless experience from signup.', timeAgo: '9 months ago' },
  { id: 'zw-13', name: 'Khama Billiat', countryCode: 'ZW', countryName: 'Zimbabwe', rating: 4, text: 'The security protocols give me peace.', timeAgo: '10 months ago' },
  { id: 'zw-14', name: 'Knowledge Musona', countryCode: 'ZW', countryName: 'Zimbabwe', rating: 5, text: 'Impressive yields and transparent ops.', timeAgo: '11 months ago' },
  { id: 'zw-15', name: 'Tinashe Nengomasha', countryCode: 'ZW', countryName: 'Zimbabwe', rating: 5, text: 'Good platform for institutional grade.', timeAgo: '1 year ago' },
  { id: 'zw-16', name: 'Marvelous Nakamba', countryCode: 'ZW', countryName: 'Zimbabwe', rating: 5, text: 'Tavari is the future of wealth.', timeAgo: '1 year ago' },
  { id: 'zw-17', name: 'Charles Manyuchi', countryCode: 'ZW', countryName: 'Zimbabwe', rating: 4, text: 'The regular plan is perfect.', timeAgo: '1 year ago' },
  { id: 'zw-18', name: 'Hopewell Chin\'ono', countryCode: 'ZW', countryName: 'Zimbabwe', rating: 5, text: 'Exceptional service and rewarding.', timeAgo: '1 year ago' },
  { id: 'zw-19', name: 'Tsitsi Dangarembga', countryCode: 'ZW', countryName: 'Zimbabwe', rating: 5, text: 'Finally a platform that delivers.', timeAgo: '2 years ago' },
  { id: 'zw-20', name: 'Dambudzo Marechera', countryCode: 'ZW', countryName: 'Zimbabwe', rating: 5, text: 'The user experience is premium.', timeAgo: '2 years ago' },
];

export interface Investor {
  id: string;
  name: string;
  countryCode: string;
  countryName: string;
  amount: number;
  dailyRoi: number;
  rank: number;
  photoURL?: string;
}

export const TOP_INVESTORS: Investor[] = [
  { 
    id: 'inv-1', 
    name: 'Lord Sterling', 
    countryCode: 'GB', 
    countryName: 'UK', 
    amount: 3800000, 
    dailyRoi: 110200, 
    rank: 1,
    photoURL: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&h=200&auto=format&fit=crop'
  },
  { 
    id: 'inv-2', 
    name: 'Olu Jide', 
    countryCode: 'NG', 
    countryName: 'Nigeria', 
    amount: 3250000, 
    dailyRoi: 94250, 
    rank: 2,
    photoURL: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&h=200&auto=format&fit=crop'
  },
  { 
    id: 'inv-3', 
    name: 'Chen Wei', 
    countryCode: 'CN', 
    countryName: 'China', 
    amount: 2900000, 
    dailyRoi: 84100, 
    rank: 3,
    photoURL: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?q=80&w=200&h=200&auto=format&fit=crop'
  },
  { 
    id: 'inv-4', 
    name: 'Marcus Tan', 
    countryCode: 'SG', 
    countryName: 'Singapore', 
    amount: 2100000, 
    dailyRoi: 60900, 
    rank: 4,
    photoURL: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=200&h=200&auto=format&fit=crop'
  },
  { 
    id: 'inv-5', 
    name: 'Sarah Miller', 
    countryCode: 'US', 
    countryName: 'US', 
    amount: 1850000, 
    dailyRoi: 53650, 
    rank: 5,
    photoURL: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&h=200&auto=format&fit=crop'
  },
  { 
    id: 'inv-6', 
    name: 'Juma Hassan', 
    countryCode: 'TZ', 
    countryName: 'Tanzania', 
    amount: 1200000, 
    dailyRoi: 34800, 
    rank: 6,
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=juma'
  },
  { 
    id: 'inv-7', 
    name: 'Thabo Ndlovu', 
    countryCode: 'ZA', 
    countryName: 'South Africa', 
    amount: 850000, 
    dailyRoi: 22950, 
    rank: 7,
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=thabo'
  },
  { 
    id: 'inv-8', 
    name: 'Wong Ka-shing', 
    countryCode: 'HK', 
    countryName: 'Hong Kong', 
    amount: 620000, 
    dailyRoi: 16740, 
    rank: 8,
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=wong'
  },
  { 
    id: 'inv-9', 
    name: 'Lindiwe Dlamini', 
    countryCode: 'ZA', 
    countryName: 'South Africa', 
    amount: 520000, 
    dailyRoi: 14040, 
    rank: 9,
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lindiwe'
  },
  { 
    id: 'inv-10', 
    name: 'Ayo Moses', 
    countryCode: 'NG', 
    countryName: 'Nigeria', 
    amount: 480000, 
    dailyRoi: 12960, 
    rank: 10,
    photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=moses'
  },
  { id: 'inv-11', name: 'Elena Rossi', countryCode: 'IT', countryName: 'Italy', amount: 450000, dailyRoi: 12150, rank: 11, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=elena' },
  { id: 'inv-12', name: 'Hiroshi Tanaka', countryCode: 'JP', countryName: 'Japan', amount: 425000, dailyRoi: 11475, rank: 12, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=hiroshi' },
  { id: 'inv-13', name: 'Amira Mansour', countryCode: 'EG', countryName: 'Egypt', amount: 410000, dailyRoi: 11070, rank: 13, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=amira' },
  { id: 'inv-14', name: 'Lukas Fischer', countryCode: 'DE', countryName: 'Germany', amount: 395000, dailyRoi: 10665, rank: 14, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lukas' },
  { id: 'inv-15', name: 'Sofia Silva', countryCode: 'BR', countryName: 'Brazil', amount: 380000, dailyRoi: 10260, rank: 15, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sofia' },
  { id: 'inv-16', name: 'Liam O\'Connor', countryCode: 'IE', countryName: 'Ireland', amount: 365000, dailyRoi: 9855, rank: 16, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=liam' },
  { id: 'inv-17', name: 'Alya Volkova', countryCode: 'RU', countryName: 'Russia', amount: 350000, dailyRoi: 9450, rank: 17, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alya' },
  { id: 'inv-18', name: 'Mateo Garcia', countryCode: 'ES', countryName: 'Spain', amount: 340000, dailyRoi: 9180, rank: 18, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mateo' },
  { id: 'inv-19', name: 'Chloe Dubois', countryCode: 'FR', countryName: 'France', amount: 330000, dailyRoi: 8910, rank: 19, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=chloe' },
  { id: 'inv-20', name: 'Arjun Gupta', countryCode: 'IN', countryName: 'India', amount: 320000, dailyRoi: 8640, rank: 20, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=arjun' },
  { id: 'inv-21', name: 'Isabella Hernandez', countryCode: 'MX', countryName: 'Mexico', amount: 310000, dailyRoi: 8370, rank: 21, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=isabella' },
  { id: 'inv-22', name: 'Noah Wilson', countryCode: 'CA', countryName: 'Canada', amount: 300000, dailyRoi: 8100, rank: 22, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=noah' },
  { id: 'inv-23', name: 'Mia Andersen', countryCode: 'DK', countryName: 'Denmark', amount: 290000, dailyRoi: 7830, rank: 23, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mia' },
  { id: 'inv-24', name: 'Oliver Smith', countryCode: 'AU', countryName: 'Australia', amount: 280000, dailyRoi: 7560, rank: 24, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=oliver' },
  { id: 'inv-25', name: 'Fatima Al-Said', countryCode: 'AE', countryName: 'UAE', amount: 275000, dailyRoi: 7425, rank: 25, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=fatima' },
  { id: 'inv-26', name: 'Sven Berg', countryCode: 'SE', countryName: 'Sweden', amount: 270000, dailyRoi: 7290, rank: 26, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sven' },
  { id: 'inv-27', name: 'Ji-won Kim', countryCode: 'KR', countryName: 'South Korea', amount: 265000, dailyRoi: 7155, rank: 27, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jiwon' },
  { id: 'inv-28', name: 'Ahmed Hassan', countryCode: 'SA', countryName: 'Saudi Arabia', amount: 260000, dailyRoi: 7020, rank: 28, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ahmed' },
  { id: 'inv-29', name: 'Yuki Nakamura', countryCode: 'JP', countryName: 'Japan', amount: 255000, dailyRoi: 6885, rank: 29, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=yuki' },
  { id: 'inv-30', name: 'Larissa Santos', countryCode: 'BR', countryName: 'Brazil', amount: 250000, dailyRoi: 6750, rank: 30, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=larissa' },
  { id: 'inv-31', name: 'Priya Sharma', countryCode: 'IN', countryName: 'India', amount: 245000, dailyRoi: 6615, rank: 31, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya' },
  { id: 'inv-32', name: 'Thomas Mueller', countryCode: 'DE', countryName: 'Germany', amount: 240000, dailyRoi: 6480, rank: 32, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=thomas' },
  { id: 'inv-33', name: 'Emma Johnson', countryCode: 'US', countryName: 'USA', amount: 235000, dailyRoi: 6345, rank: 33, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emma' },
  { id: 'inv-34', name: 'Gabriel Martinez', countryCode: 'ES', countryName: 'Spain', amount: 230000, dailyRoi: 6210, rank: 34, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=gabriel' },
  { id: 'inv-35', name: 'Hanna Lindholm', countryCode: 'FI', countryName: 'Finland', amount: 225000, dailyRoi: 6075, rank: 35, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=hanna' },
  { id: 'inv-36', name: 'Omer Farooq', countryCode: 'PK', countryName: 'Pakistan', amount: 220000, dailyRoi: 5940, rank: 36, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=omer' },
  { id: 'inv-37', name: 'Nikoletta Pappas', countryCode: 'GR', countryName: 'Greece', amount: 215000, dailyRoi: 5805, rank: 37, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=nikoletta' },
  { id: 'inv-38', name: 'Zoltan Nagy', countryCode: 'HU', countryName: 'Hungary', amount: 210000, dailyRoi: 5670, rank: 38, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=zoltan' },
  { id: 'inv-39', name: 'Anikó Kovács', countryCode: 'HU', countryName: 'Hungary', amount: 205000, dailyRoi: 5535, rank: 39, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aniko' },
  { id: 'inv-40', name: 'Karel Novak', countryCode: 'CZ', countryName: 'Czech Republic', amount: 200000, dailyRoi: 5400, rank: 40, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=karel' },
  { id: 'inv-41', name: 'Marta Nowak', countryCode: 'PL', countryName: 'Poland', amount: 195000, dailyRoi: 5265, rank: 41, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=marta' },
  { id: 'inv-42', name: 'Sven Gustafsson', countryCode: 'SE', countryName: 'Sweden', amount: 190000, dailyRoi: 5130, rank: 42, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sven2' },
  { id: 'inv-43', name: 'Elena Petrova', countryCode: 'BG', countryName: 'Bulgaria', amount: 185000, dailyRoi: 4995, rank: 43, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=elena2' },
  { id: 'inv-44', name: 'Rafael Silva', countryCode: 'PT', countryName: 'Portugal', amount: 180000, dailyRoi: 4860, rank: 44, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rafael' },
  { id: 'inv-45', name: 'Ingrid Meyer', countryCode: 'CH', countryName: 'Switzerland', amount: 175000, dailyRoi: 4725, rank: 45, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ingrid' },
  { id: 'inv-46', name: 'Hans De Jong', countryCode: 'NL', countryName: 'Netherlands', amount: 170000, dailyRoi: 4590, rank: 46, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=hans' },
  { id: 'inv-47', name: 'Anna Lindgren', countryCode: 'NO', countryName: 'Norway', amount: 165000, dailyRoi: 4455, rank: 47, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=anna' },
  { id: 'inv-48', name: 'Paul Clarke', countryCode: 'NZ', countryName: 'New Zealand', amount: 160000, dailyRoi: 4320, rank: 48, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=paul' },
  { id: 'inv-49', name: 'Dimitri Ivanov', countryCode: 'UA', countryName: 'Ukraine', amount: 155000, dailyRoi: 4185, rank: 49, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=dimitri' },
  { id: 'inv-50', name: 'Fatima Zahra', countryCode: 'MA', countryName: 'Morocco', amount: 150000, dailyRoi: 4050, rank: 50, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=fatima2' },
  { id: 'inv-51', name: 'Kenji Sato', countryCode: 'JP', countryName: 'Japan', amount: 145000, dailyRoi: 3915, rank: 51, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=kenji' },
  { id: 'inv-52', name: 'Lucia Romano', countryCode: 'IT', countryName: 'Italy', amount: 140000, dailyRoi: 3780, rank: 52, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lucia' },
  { id: 'inv-53', name: 'Marko Jovic', countryCode: 'RS', countryName: 'Serbia', amount: 135000, dailyRoi: 3645, rank: 53, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=marko' },
  { id: 'inv-54', name: 'Sonia Gupta', countryCode: 'IN', countryName: 'India', amount: 130000, dailyRoi: 3510, rank: 54, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sonia' },
  { id: 'inv-55', name: 'Anders Nyman', countryCode: 'SE', countryName: 'Sweden', amount: 125000, dailyRoi: 3375, rank: 55, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=anders' },
  { id: 'inv-56', name: 'Tariq Al-Farsi', countryCode: 'OM', countryName: 'Oman', amount: 120000, dailyRoi: 3240, rank: 56, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tariq' },
  { id: 'inv-57', name: 'Mei Ling', countryCode: 'CN', countryName: 'China', amount: 115000, dailyRoi: 3105, rank: 57, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=meiling' },
  { id: 'inv-58', name: 'Rohan Deshmukh', countryCode: 'IN', countryName: 'India', amount: 110000, dailyRoi: 2970, rank: 58, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rohan' },
  { id: 'inv-59', name: 'Carmen Rojas', countryCode: 'CL', countryName: 'Chile', amount: 105000, dailyRoi: 2835, rank: 59, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=carmen' },
  { id: 'inv-60', name: 'Klaus Schmidt', countryCode: 'AT', countryName: 'Austria', amount: 100000, dailyRoi: 2700, rank: 60, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=klaus' },
  { id: 'inv-61', name: 'Ji-seon Lee', countryCode: 'KR', countryName: 'South Korea', amount: 95000, dailyRoi: 2565, rank: 61, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jiseon' },
  { id: 'inv-62', name: 'Omar Bakri', countryCode: 'LB', countryName: 'Lebanon', amount: 90000, dailyRoi: 2430, rank: 62, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=omar' },
  { id: 'inv-63', name: 'Hélène Leroy', countryCode: 'BE', countryName: 'Belgium', amount: 85000, dailyRoi: 2295, rank: 63, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=helene' },
  { id: 'inv-64', name: 'Pavel Kuznetsov', countryCode: 'RU', countryName: 'Russia', amount: 80000, dailyRoi: 2160, rank: 64, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=pavel' },
  { id: 'inv-65', name: 'Sandra Bullock', countryCode: 'US', countryName: 'USA', amount: 75000, dailyRoi: 2025, rank: 65, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sandra' },
  { id: 'inv-66', name: 'Diego Torres', countryCode: 'AR', countryName: 'Argentina', amount: 70000, dailyRoi: 1890, rank: 66, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=diego' },
  { id: 'inv-67', name: 'Fatima Jinnah', countryCode: 'PK', countryName: 'Pakistan', amount: 65000, dailyRoi: 1755, rank: 67, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=fatima3' },
  { id: 'inv-68', name: 'Lars Nielsen', countryCode: 'DK', countryName: 'Denmark', amount: 60000, dailyRoi: 1620, rank: 68, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lars' },
  { id: 'inv-69', name: 'Emma Wilson', countryCode: 'AU', countryName: 'Australia', amount: 55000, dailyRoi: 1485, rank: 69, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emma2' },
  { id: 'inv-70', name: 'Chen Hao', countryCode: 'CN', countryName: 'China', amount: 50000, dailyRoi: 1350, rank: 70, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=chenhao' },
  { id: 'inv-71', name: 'Sara Costa', countryCode: 'PT', countryName: 'Portugal', amount: 48000, dailyRoi: 1296, rank: 71, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sara' },
  { id: 'inv-72', name: 'Oksana Shevchenko', countryCode: 'UA', countryName: 'Ukraine', amount: 46000, dailyRoi: 1242, rank: 72, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=oksana' },
  { id: 'inv-73', name: 'Matteo Colombo', countryCode: 'IT', countryName: 'Italy', amount: 44000, dailyRoi: 1188, rank: 73, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=matteo2' },
  { id: 'inv-74', name: 'Isabelle Maes', countryCode: 'BE', countryName: 'Belgium', amount: 42000, dailyRoi: 1134, rank: 74, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=isabelle' },
  { id: 'inv-75', name: 'David Smith', countryCode: 'UK', countryName: 'UK', amount: 40000, dailyRoi: 1080, rank: 75, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david' },
  { id: 'inv-76', name: 'Ayo Balogun', countryCode: 'NG', countryName: 'Nigeria', amount: 38000, dailyRoi: 1026, rank: 76, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ayo' },
  { id: 'inv-77', name: 'Elena Koroleva', countryCode: 'RU', countryName: 'Russia', amount: 36000, dailyRoi: 972, rank: 77, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=elena3' },
  { id: 'inv-78', name: 'Marek Jankowski', countryCode: 'PL', countryName: 'Poland', amount: 34000, dailyRoi: 918, rank: 78, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=marek' },
  { id: 'inv-79', name: 'Yuki Watanabe', countryCode: 'JP', countryName: 'Japan', amount: 32000, dailyRoi: 864, rank: 79, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=yuki2' },
  { id: 'inv-80', name: 'Sophia Chen', countryCode: 'CA', countryName: 'Canada', amount: 30000, dailyRoi: 810, rank: 80, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sophia' },
  { id: 'inv-81', name: 'Lucas Dubois', countryCode: 'FR', countryName: 'France', amount: 28000, dailyRoi: 756, rank: 81, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lucas2' },
  { id: 'inv-82', name: 'Hanna Bjork', countryCode: 'NO', countryName: 'Norway', amount: 26000, dailyRoi: 702, rank: 82, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=hanna2' },
  { id: 'inv-83', name: 'Fatih Terim', countryCode: 'TR', countryName: 'Turkey', amount: 24000, dailyRoi: 648, rank: 83, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=fatih' },
  { id: 'inv-84', name: 'Leyla Gunes', countryCode: 'TR', countryName: 'Turkey', amount: 22000, dailyRoi: 594, rank: 84, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=leyla' },
  { id: 'inv-85', name: 'Ivan Horvat', countryCode: 'HR', countryName: 'Croatia', amount: 20000, dailyRoi: 540, rank: 85, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ivan' },
  { id: 'inv-86', name: 'Amalie Jensen', countryCode: 'DK', countryName: 'Denmark', amount: 18000, dailyRoi: 486, rank: 86, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=amalie' },
  { id: 'inv-87', name: 'Liam Davies', countryCode: 'AU', countryName: 'Australia', amount: 16000, dailyRoi: 432, rank: 87, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=liam2' },
  { id: 'inv-88', name: 'Mateo Lopez', countryCode: 'CO', countryName: 'Colombia', amount: 14000, dailyRoi: 378, rank: 88, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mateo3' },
  { id: 'inv-89', name: 'Anya Sharma', countryCode: 'IN', countryName: 'India', amount: 12000, dailyRoi: 324, rank: 89, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=anya' },
  { id: 'inv-90', name: 'Koji Yamamoto', countryCode: 'JP', countryName: 'Japan', amount: 10000, dailyRoi: 270, rank: 90, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=koji' },
  { id: 'inv-91', name: 'Elena Dimitrova', countryCode: 'BG', countryName: 'Bulgaria', amount: 9000, dailyRoi: 243, rank: 91, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=elena4' },
  { id: 'inv-92', name: 'Markus Weber', countryCode: 'AT', countryName: 'Austria', amount: 8000, dailyRoi: 216, rank: 92, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=markus' },
  { id: 'inv-93', name: 'Silvia Conti', countryCode: 'IT', countryName: 'Italy', amount: 7500, dailyRoi: 202, rank: 93, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=silvia' },
  { id: 'inv-94', name: 'Joao Silva', countryCode: 'BR', countryName: 'Brazil', amount: 7000, dailyRoi: 189, rank: 94, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=joao' },
  { id: 'inv-95', name: 'Nathalie Meyer', countryCode: 'CH', countryName: 'Switzerland', amount: 6500, dailyRoi: 175, rank: 95, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=nathalie' },
  { id: 'inv-96', name: 'Ole Hansen', countryCode: 'NO', countryName: 'Norway', amount: 6000, dailyRoi: 162, rank: 96, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ole' },
  { id: 'inv-97', name: 'Fatima Al-Khatib', countryCode: 'JO', countryName: 'Jordan', amount: 5500, dailyRoi: 148, rank: 97, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=fatima4' },
  { id: 'inv-98', name: 'Artem Novikov', countryCode: 'UA', countryName: 'Ukraine', amount: 5000, dailyRoi: 135, rank: 98, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=artem' },
  { id: 'inv-99', name: 'Svenja Mueller', countryCode: 'DE', countryName: 'Germany', amount: 4500, dailyRoi: 121, rank: 99, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=svenja' },
  { id: 'inv-100', name: 'Ali Ahmed', countryCode: 'QA', countryName: 'Qatar', amount: 4000, dailyRoi: 108, rank: 100, photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aliahmed' },
];
